name: Overwrite readme file

on:
  schedule:
    - cron: '* * * * *'
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: README.md
          write-mode: overwrite
          contents: |
            <img src="https://raw.githubusercontent.com/ZenixCodez/ZenixCodez/main/assets/banner.png" />

            ## About Me 🗒️
            Hey, cosmic voyagers! I'm **Zenix**, touching down from the Andromeda galaxy. I've been in the <ins>**Full-Stack development**</ins> field for a stellar five years, dancing with an array of projects that groove to the beats of diverse and budding technologies. Buckle up and dive into my GitHub galaxy – your love's the fuel that keeps this starship soaring!

            ```ts
            const zenix = {
                From: "The Andromeda Galaxy",
                Languages: ["JavaScript", "Python", "TypeScript", "Java", "C#"],
                TotalCommits: {{ COMMITS }},
                StarsGiven: {{ STARS }},
                Repositories: {{ REPOSITORIES }},
                TotalContributedRepos: {{ REPOSITORIES_CONTRIBUTED_TO }},
            };
            ```
      - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "ReadME Reset"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        fi