name: stats updater

on:
  workflow_run:
    workflows: ["Overwrite readme file"]
    branches: [main]
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          template: ./README.md
      - name: Commit & Push
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "[Automatic] Updated Stats ReadMe.md"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          fi
